idle.threshold.seconds=2

reminder.audio.enabled=true
reminder.audio.file=C:\Users\ferdi\IdeaProjects\idleCheck\src\main\resources\AFKReminderAudio.wav

reminder.image.enabled=true
reminder.image.file=C:\Users\ferdi\IdeaProjects\idleCheck\src\main\resources\AFKReminderImage.png

reminder.video.enabled=true
reminder.video.file=C:\Users\ferdi\IdeaProjects\idleCheck\src\main\resources\AFKReminderVideo.mp4