idle.threshold.seconds=4

reminder.audio.enabled=true
reminder.audio.file=ArgSacrifice.wav

reminder.image.enabled=false
reminder.image.file=LTGEducate.png

reminder.video.enabled=false
reminder.video.file=C:/Users/ferdi/Downloads/007FirstLightEdit.mp4